ror_version/config/routes.rb
Rails.application.routes.draw do
  root "pages#main"

  get '/main' => 'pages#main'
  get '/procedure' => 'pages#procedure'
  get '/qna' => 'pages#qna'
  
  get '/d2setup' => 'pages#d2setup'
  get '/map' => 'pages#map'
  get '/chooseClass' => 'pages#chooseClass'
  
  get '/shopping' => 'pages#shopping'
  get '/newtonA' => 'pages#newtonA'
  get '/essentialShopping' =>'pages#essentialShopping'
  get '/curricular' => 'pages#curricular'
  get '/studentAssociation' => 'pages#studentAssociation'
  get '/alumnian' => 'pages#alumnian'

  get '/stunionIntro' => 'pages#stunionIntro'
  
end

ror_version/app/models/newcomer_club.rb
class NewcomerClub < ActiveRecord::Base
    # must contain :category & :name
    validates_presence_of :category, :name

    # validate :pdf, :fb, :web value
    validates_format_of :pdf, :with => /.+\.pdf/, :allow_nil => true
    validates_format_of :fb, :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix, :allow_nil => true
    validates_format_of :web, :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix, :allow_nil => true

    # validate :category, :color value
    validates_inclusion_of :category, :in => ["curricular", "studentAssociation", "alumnian"]
    validates_inclusion_of :color, :in => ["white", "milk", "grey", "default"], :allow_nil => true
end

ror_version/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def curricular
    @title = "社團資訊 | 網路新生包"
    @data = NewcomerClub.where(:category => "curricular")
  end
  def studentAssociation
    @title = "系學會 | 網路新生包"
    @data = NewcomerClub.where(:category => "studentAssociation")
  end
  def alumnian
    @title = "友會列表 ｜ 網路新生包"   
    @data = NewcomerClub.where(:category => "alumnian")
  end
  def main
    @title = "首頁 | 網路新生包"
  end
  def procedure 
    @title = "重要程序 | 網路新生包"
  end
  def qna
    @title = "精選問答 | 網路新生包"
  end
  def d2setup
    @title = "D2與宿網設置 | 網路新生包"
  end
  def chooseClass
    @title = "選課教學 | 網路新生包"
  end
  def map
    @title = "交大地圖 | 網路新生包"
  end
  def shopping
    @title = "新生團購 | 網路新生包"
  end 
  def newtonA
    @title = "金牛頓學生特價 | 網路新生包"
  end
  def stunionIntro
    @title = "學聯會介紹 | 網路新生包"
  end
end

ror_version/app/helpers/application_helper.rb
module ApplicationHelper
	def render_title
	  return @title if defined?(@title)
	  "網路新生包"
	end
end

ror_version/app/helpers/landing_helper.rb
module LandingHelper
end

ror_version/app/helpers/pages_helper.rb
module PagesHelper
end

ror_version/app/views/layouts/_footer.html.erb
<footer class="footer-custom">
<div class="row footer-upper-bar">
  <div class="col-lg-2 col-lg-offset-1 col-sm-3">
    <ul>
      <li class="footer-header">關於</li>
      <li><a href="https://plus.nctu.edu.tw" target="_blank">關於NCTU+</a></li>
      <li><a href="https://stunion.nctu.edu.tw/blog/" target="_blank">關於學聯會</a></li>
      <li><a href="http://stunion.nctu.edu.tw/question/" target="_blank">新生提問平台</a></li>
      <li><%= link_to "學聯會徵才", stunionIntro_path %></li>
    </ul>
  </div>
  <div class="col-lg-2 col-sm-3">
    <ul>
      <li class="footer-header">團購</li>
      <li><%= link_to "小七團購", essentialShopping_path(anchor: "top") %></li>
      <li><%= link_to "金牛頓團購", newtonA_path %></li>
      <li><%= link_to "計算機團購", shopping_path(anchor: "calculator") %></li>
      <li><%= link_to "桌燈團購", shopping_path(anchor: "lamp") %></li>
    </ul>
  </div>
  <div class="col-lg-2 col-sm-3">
    <ul>
      <li class="footer-header">網路新生包</li>
      <li><%= link_to "D2宿網申請", d2setup_path %></li>
      <li><%= link_to "選課教學", chooseClass_path %></li>
      <li><%= link_to "社團介紹", curricular_path %></li>
      <li><%= link_to "系學會", studentAssociation_path %></li>
      <li><%= link_to "友會介紹", alumnian_path %></li>
    </ul>
  </div>
  <div class="col-lg-4 col-lg-offset-1 col-sm-3">
    <%#<a href="https://stunion.nctu.edu.tw/blog/" target="_blank"><img src="assets/logo.png" class="footer-logo"></a>%>
    <%#<a href="https://plus.nctu.edu.tw" target="_blank"><img src="assets/nctuplus.png" class="footer-logo">	</a>%>
    <a href="https://stunion.nctu.edu.tw/blog/" target="_blank"><%= image_tag 'logo.png', :class => 'footer-logo' %></a>
    <a href="https://plus.nctu.edu.tw" target="_blank"><%= image_tag 'nctuplus.png', :class => 'footer-logo' %></a>
    <div class="footer-lower-bar">
      <span>© Copy Rights 2016 交大學聯會資訊部、NCTU+ </span>
    </div>
  </div>
</div>
</footer>
<div class="ribbon-top"></div>

ror_version/app/views/layouts/_header.html.erb
<nav class="navbar <%= action_name == 'main' ? 'navbar-custom' : 'navbar-custom2' %> navbar-fixed-top" role="navigation" id="top">
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
            <i class="fa fa-bars"></i>
        </button>
        <span class="navbar-brand"><%= link_to "網路新生包", main_path %></span>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-main-collapse">
        <ul class="nav navbar-nav">
            <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
            <li class="hidden">
            <a href="#page-top"></a>
            </li>
            <li> 
            <%= link_to "初入交大", procedure_path %>
            </li> 
            <li> 
            <%= link_to "精選問答", qna_path %>
            </li> 
            <li class="dropdown"> 
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">團購 <span class="caret"></span></a> 
            <ul class="dropdown-menu"> 
                <li><%= link_to "新生團購", shopping_path(anchor: "top") %></li>
                <li><%= link_to "Newton'sA 學生特價", newtonA_path %></li>
                <li><%= link_to "小七精美用品促銷", essentialShopping_path(anchor: "top") %></li>
            </ul>
            </li> 
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">社團 X 系學會 X 友會資訊 <span class="caret"></span></a> 
                <ul class="dropdown-menu">
                    <li><%= link_to "社團資訊", curricular_path %></li>
                    <li><%= link_to "系學會", studentAssociation_path %></li>
                    <li><%= link_to "友會", alumnian_path %></li>
                </ul> 
            </li> 
            <li> 
            <%= link_to "交大地圖", map_path %>
            </li> 
            <li><%= link_to "D2帳號申請", d2setup_path %></li> 
            <li><%= link_to "選課教學", chooseClass_path %></li> 
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

ror_version/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="NCTU 網路新生包">
        <meta name="keywords" content="NCTU網路新生包,交大網路新生包,網路新生包,交大新生包,NCTU新生包,新生包,交大新生,NCTU新生,交大學聯會,NCTU,交大">
        <meta name="author" content="交通大學學聯會資訊部">
        <meta name="robots" content="index,follow">
        <meta property = "og:site_name" content="交通大學網路新生包">
        <meta property = "og:image" content = "assets/logo.png">
        <meta property = "og:url" content="https://www.nctuplus.com">
        <meta property = "og:type" content="website">
        <meta property = "og:description" content="交大新生絕對不能錯過的網路新生包">
        <meta property = "og:title" content="交通大學網路新生包">
        <title><%= render_title %></title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <link rel="shortcut icon" href="assets/logo.png">
        <%= stylesheet_link_tag 'newcomer-2' %>
        <%= stylesheet_link_tag 'newcomer' %>
    </head>
    <body>
        <%= render "layouts/header" %>
        <%= yield %>
        <%= render "layouts/footer" %>
        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-81683881-2', 'auto');
  ga('send', 'pageview');

</script>
        <%= javascript_include_tag 'newcomer' %>
    </body>
</html>

ror_version/app/views/pages/_club.html.erb
<% datas.each_with_index do |club, counter| %>
    <% if club[:img] != nil %>
        <% if counter%2 == 0 %>
            <% # image left %>
            <%= render 'club_info', :club => club, :category => category, :push => true %>
            <%= render 'club_img', :club => club, :category => category, :pull => true %>
        <% else %>
            <% # image right %>
            <%= render 'club_info', :club => club, :category => category, :push => false %>
            <%= render 'club_img', :club => club, :category => category, :pull => false %>
        <% end %>
    <% else %>
        <% # only render info %>
        <%= render 'club_info', :club => club, :category => category, :push => false %>
    <% end %>
<% end %>

ror_version/app/views/pages/_club_img.html.erb
<% if pull %>
    <% if club[:color] == "white" %> 
        <div class="col-sm-6 col-sm-pull-6 pic-col minor-1">
    <% elsif club[:color] == "milk" %> 
        <div class="col-sm-6 col-sm-pull-6 pic-col minor-2">
    <% elsif club[:color] == "grey" %> 
        <div class="col-sm-6 col-sm-pull-6 pic-col minor-3">
    <% else %>
        <div class="col-sm-6 col-sm-pull-6 pic-col">
    <% end %>
<% else %>
    <% if club[:color] == "white" %> 
        <div class="col-sm-6 pic-col minor-1">
    <% elsif club[:color] == "milk" %> 
        <div class="col-sm-6 pic-col minor-2">
    <% elsif club[:color] == "grey" %> 
        <div class="col-sm-6 pic-col minor-3">
    <% else %>
        <div class="col-sm-6 pic-col">
    <% end %>
<% end %>
    <%= image_tag club[:category]+'/'+club[:img] %>
</div>

ror_version/app/views/pages/_club_info.html.erb
<% if push %>
    <div class="col-sm-6 col-sm-push-6 text-col">
<% else %>
    <div class="col-sm-6 text-col">
<% end %>
    <h3><%= club[:name] %></h3>
    <hr>
    <section class="icons">
    <% if club[:fb] != nil %>
        <%= link_to club[:fb], :target => '_blank' do %>
            <p><i class="fa fa-facebook-official fa-lg"></i></p>
        <% end %>
    <% end %>
    <% if club[:web] != nil %>
        <%= link_to club[:web], :target => '_blank' do %>
            <p><i class="fa fa-chrome fa-lg"></i></p>
        <% end %>
    <% end %>
    <% if club[:pdf] != nil %>
        <%= link_to "pdf/#{category}/#{club[:pdf]}", :target => '_blank' do %>
            <p>PDF</p>
        <% end %>
    <% end %>
    <% if club[:group] != nil %>
        <%= link_to club[:group], :target => '_blank' do %>
            <p>新生</p>
        <% end %>
    <% end %>
    </section>
</div>

ror_version/app/views/pages/_header2.html.erb
       <nav class="navbar navbar-custom2 navbar-fixed-top" role="navigation" id="top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <span class="navbar-brand"><%= link_to "NCTU", main_path %></span>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                         <li> 
                             <%= link_to "初入交大", procedure_path %>
                         </li> 
                         <li> 
                             <%= link_to "精選問答", qna_path %>
                         </li> 
                         <li class="dropdown"> 
                             <a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">團購 <span class="caret"></span></a> 
                             <ul class="dropdown-menu"> 
                                <li><%= link_to "新生團購", shopping_path(anchor: "top") %></li>
                                <li><%= link_to "Newton'sA 學生特價", newtonA_path %></li>
                                <li><%= link_to "小七精美用品促銷", essentialShopping_path(anchor: "top") %></li>
                            </ul>
                         </li> 
                         <li class="dropdown">
                            <a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">社團 X 系學會 X 友會資訊 <span class="caret"></span></a> 
                            <ul class="dropdown-menu">
                                <li><%= link_to "社團資訊", curricular_path %></li>
                                <li><%= link_to "系學會", studentAssociation_path %></li>
                                <li><%= link_to "友會", alumnian_path %></li>
                            </ul> 
                         </li> 
                         <li> 
                             <%= link_to "交大地圖", map_path %>
                         </li> 
                         <li class="dropdown"> 
                           <a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">教學 <span class="caret"></span></a> 
                                <ul class="dropdown-menu"> 
                                    <li><%= link_to "D2帳號申請", d2setup_path %></li> 
                                    <li><%= link_to "選課教學", chooseClass_path %></li> 
                                </ul> 
                         </li> 
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

ror_version/app/views/pages/alumnian.html.erb
<%= stylesheet_link_tag 'curricular' %>
<div class="spacing"></div>
<section class="curricular">
<span><h3>友會列表</h3></span>

<%= render 'club', :category => 'alumnian', :datas => @data %>

<div class="row important">
    <div class="col-sm-12">
        <h4>(註：友會資料陸續增加中！該欄空白代表該友會並未提供該項資料。此表並非所有友會，僅為有提供資料之友會)
            <p>以上資料由各友會提供，並不代表學聯會立場</p>
        </h4>
    </div>
</div>
</section>

ror_version/app/views/pages/chooseClass.html.erb
<%= stylesheet_link_tag 'chooseClass' %>

<div class="spacing"></div>
<div class="cover">
    <div class="container course">

        <div class="row">
            <div class="group">
                <caption>模擬排課</caption>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">0.</div>
                    </div>
                    <div class="text">進入NCTU+首頁，進行登入動作</div>
                </div>
                <div class="content">
                    NCTU+可同時挷定交大E3、Facebook、Google+帳號。
                    <%= image_tag 'chooseClass/0.png', :class => "img-responsive" %>
                </div>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">1.</div>
                    </div>
                    <div class="text">
                        進入模擬排課頁面
                    </div>
                </div>
                <div class="content">
                    <%= image_tag 'chooseClass/1.png', :class => "img-responsive" %>
                </div>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">2.</div>
                    </div>
                    <div class="text">參考交大的課程時間表</div>
                </div>
                <div class="content">
                    可以查詢自己科系的必修及選修科目。<br>
                    在課程時間表首頁可找到代表課堂時間(如: 2GH)及教室地點(如: EC315)的代碼參考表。				
                    <%= image_tag 'chooseClass/3.png', :class => "img-responsive" %>
                </div>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">3.</div>
                    </div>
                    <div class="text">在NCTU+模擬排課中查詢欲選的課程</div>
                </div>
                <div class="content">
                    舉凡課名、教授、時間等篩選條件皆可直接查詢。<br>
                    按下"+"即可選中，在右方的課表中加入該課程。<br>
                    按下"★"即收藏該課程。
                    <%= image_tag 'chooseClass/4.png', :class => "img-responsive" %>
                </div>	
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">4.</div>
                    </div>
                    <div class="text">衝堂判定功能</div>
                </div>
                <div class="content">
                    若選到與已選的課程時間重疊的話，則會出現「衝堂」警示。
                    <%= image_tag 'chooseClass/5.png', :class => "img-responsive" %>
                </div>

            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">5.</div>
                    </div>
                    <div class="text">空堂排課功能</div>
                </div>
                <div class="content">
                    若想在剩餘的空堂選一些通識或選修課程，可以在右方課表先選取可接受的時間，再按下"空堂"按鈕，輕鬆挑選不會衝堂的課程。
                    <%= image_tag 'chooseClass/6.png', :class => "img-responsive" %>
                    <%= image_tag 'chooseClass/7.png', :class => "img-responsive" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="group">
                <caption>正式排課</caption>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">0.</div>
                    </div>
                    <div class="text">進入交大選課系統</div>
                </div>
                <div class="content">
                    <%= image_tag 'chooseClass/8.png', :class => "img-responsive" %>
                    <%= image_tag 'chooseClass/9.png', :class => "img-responsive" %>
                </div>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">1.</div>
                    </div>
                    <div class="text">點選「課程加退選」→「課程加選」進行加選</div>
                </div>
                <div class="content">
                    已經在NCTU+裡模擬排課過，正式選課時就能輕鬆無負擔。
                    <%= image_tag 'chooseClass/10.png', :class => "img-responsive" %>
                </div>
            </div>
            <div class="step">
                <div class="title-blk col-xs-12">
                    <div class="num">
                        <div class="mid-fix">2.</div>
                    </div>
                    <div class="text">查詢選課狀況</div>
                </div>
                <div class="content">
                    選課後可以點選「確認選課狀況」→「查詢選課狀況」來查詢。
                    <%= image_tag 'chooseClass/12.png', :class => "img-responsive" %>
                </div>
            </div>
        </div>

    </div> <!-- /container -->
</div>

ror_version/app/views/pages/curricular.html.erb
<%= stylesheet_link_tag 'curricular' %>
<div class="spacing"></div>
<section class="curricular">
    <span><h3>社團列表</h3></span>
    <%= render 'club', :category => 'curricular', :datas => @data %>

    <div class="row important">
        <div class="col-sm-12">
            <h4>(註：社團資料陸續增加中！該欄空白代表該社團並未提供該項資料。此表並非所有社團，僅為有提供資料之社團)
                <p>以上資料由各社團提供，並不代表學聯會立場</p>
            </h4>
        </div>
    </div>
</section>
	

ror_version/app/views/pages/main.html.erb
<section id="banner">
<div class="cover-pic">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-5">
            <div class="text-box"><h2>交大網路新生包</h2></div>
            <div class="text-box-2"><h2>認識交大從這裡開始</h2></div>
        </div>
    </div> 			
</div>
</section>
<section id="explore">
<div class="container">
    <h2>交大學聯會 X NCTU+</h2>
    <p>交大學聯會與NCTU+協手合作，製作歷年以來最完善的網路新生包</p>
    <p>我們希望新生們能最快地適應新學年的生活</p>
</div>
<div class="bottom">
</div>   
</section>
<section id= "procedure"> 
<div class="container">
    <h2>重要程序</h2>
    <p>註冊前須備妥之文件
    <i class="fa fa-angle-double-right"></i>
    上網登錄基本資料
    <i class="fa fa-angle-double-right"></i>
    學雜費繳費
    <i class="fa fa-angle-double-right"></i>
    選課</p>
    <p>
    <%= link_to procedure_path do %>
        <button class="btn-1">瞭解詳情</button>
    <% end %>
    </p>
</div>
<div class="bottom"></div>
</section>
<section id="shopping"> 
<div class="container">
    <h2>新生團購</h2>
    <p>
    <%= link_to shopping_path(anchor: "top") do %>
        <button class="btn-2">選購吧</button>
    <% end %>
    </p>
</div>
<div class="bottom"></div>
</section>
<section id="qna">
<div class="container">
    <h2>新生提問系統 精選問答集</h2>
    <p>
    <%= link_to qna_path do %>
        <button class="btn-3">觀看</button>
    <% end %>
    </p> 
</div>
</section>

ror_version/app/views/pages/newtonA.html.erb
<%= stylesheet_link_tag 'shopping' %>

<%#<img src="assets/shopping/newtonA.jpg" style="width:100%;">%>
<%= image_tag 'shopping/newtonA.jpg', :style => "width:100%;" %>